# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 974faa2f9e04d68bf7e13383fb2f6f2938461fb64496bf37ff1c0b094d4e4f47ed08ebb844ce45e587b11cd4259821256a3c0692cd0e8074836438c41a367a19

test:
  secret_key_base: ab4a927976226c1ad4f92802cf5bdb91c6cbd500d388ea7e29f940c1ea7919b31e351503bc9789702d7de3e327b82a9c13817f467dc21c790dc099c0e33f0818

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
